// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Prefer environment variables for configuration. Fall back to hard-coded values if env vars are not set.
const SUPABASE_URL = process.env.REACT_APP_SUPABASE_URL || process.env.VITE_SUPABASE_URL || "https://ixdalvgvnrkucwgkgyih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.REACT_APP_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4ZGFsdmd2bnJrdWN3Z2tneWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwOTIzNTUsImV4cCI6MjA4NzY2ODM1NX0.6fhAp9dYuLUpd9tHo2g8gHddv59_gDneJkU3bNZBTUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);