// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Resolve environment variables safely for both Vite (import.meta.env) and other bundlers (process.env).
// Accessing `process` directly in browser bundles can throw "process is not defined" at runtime,
// so we guard against that.
function resolveEnv() {
  // Try process.env first (for setups that polyfill/process env at build-time)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const proc: any = typeof process !== 'undefined' ? (process as any) : undefined;
  if (proc && proc.env) {
    return {
      url: proc.env.REACT_APP_SUPABASE_URL || proc.env.VITE_SUPABASE_URL || null,
      key: proc.env.REACT_APP_SUPABASE_ANON_KEY || proc.env.VITE_SUPABASE_ANON_KEY || null,
    };
  }

  // Next, try import.meta.env which Vite exposes in the browser bundle
  // @ts-ignore
  if (typeof import.meta !== 'undefined' && typeof import.meta.env !== 'undefined') {
    // @ts-ignore
    const env = import.meta.env as Record<string, unknown>;
    return {
      url: (env.VITE_SUPABASE_URL as string) || (env.REACT_APP_SUPABASE_URL as string) || null,
      key: (env.VITE_SUPABASE_ANON_KEY as string) || (env.REACT_APP_SUPABASE_ANON_KEY as string) || null,
    };
  }

  return { url: null, key: null };
}

const resolved = resolveEnv();

const SUPABASE_URL = resolved.url || "https://ixdalvgvnrkucwgkgyih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = resolved.key || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4ZGFsdmd2bnJrdWN3Z2tneWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwOTIzNTUsImV4cCI6MjA4NzY2ODM1NX0.6fhAp9dYuLUpd9tHo2g8gHddv59_gDneJkU3bNZBTUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);